Exit 1 if there are test failures

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -55,3 +55,9 @@ jobs:
         uses: im-open/process-dotnet-test-results@v2.0.0
         with:
           github-token: ${{ secrets.GITHUB_TOKEN }}
+
+     - name: Check Test Results
+       if: steps.process-trx.outputs.test-outcome == 'Failed'
+       run: |
+         echo "There were test failures."
+         exit 1
