fuck YML syntax

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -56,8 +56,8 @@ jobs:
         with:
           github-token: ${{ secrets.GITHUB_TOKEN }}
 
-     - name: Check Test Results
-       if: steps.process-trx.outputs.test-outcome == 'Failed'
-       run: |
-         echo "There were test failures."
-         exit 1
+      - name: Check Test Results
+        if: steps.process-trx.outputs.test-outcome == 'Failed'
+        run: |
+          echo "There were test failures."
+          exit 1
